Clean mod files before running them with corenenrn

diff --git a/bin/nrnivmodl.in b/bin/nrnivmodl.in
--- a/bin/nrnivmodl.in
+++ b/bin/nrnivmodl.in
@@ -2,7 +2,7 @@
 set -e
 
 ARCH=@host_cpu@
-MODSUBDIR=@modsubdir@
+MODSUBDIR="$(realpath @modsubdir@)"
 USER_PWD="$PWD"
 
 if [ -z "$NRNHOME" ] ; then
@@ -33,6 +33,10 @@ fi
 export prefix
 export bindir
 export libdir
+
+# call nrnivmodl-core if CoreNEURON is enabled and requested via CLI
+UsingCoreNEURON=false
+@CORENEURON_ENABLED_TRUE@UsingCoreNEURON=true
 
 if command -v xcrun; then
     @NRN_OSX_BUILD_TRUE@export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
@@ -76,7 +80,22 @@ while [ "$1" ] ; do
     esac
 done
 
-echo "$PWD"
+if [ "$LinkCoreNEURON" = true ] ; then
+  if [ "$UsingCoreNEURON" = true ] ; then
+    if [ "$#" -gt 1 ] ; then
+        echo "Arg Error: when called with -coreneuron only 1 mod dir is accepted."
+        exit 1
+    elif [ "$#" -eq 1 ] ; then
+      if [ -f "$1" ] || [ -f "$1.mod" ] ; then
+        echo "Arg Error: when called with -coreneuron only directories are accepted, not files."
+        exit 1
+      fi
+    fi
+  else
+    echo "Arg Error: -coreneuron is set but CoreNEURON support is not enabled."
+    exit 1
+  fi
+fi
 
 # Mod file paths may contain spaces which make variable lists of those
 # hard to manage as space is the item separator. Furthermore, when a
@@ -86,6 +105,8 @@ echo "$PWD"
 # of paths, translate the spaces for each item to +++ and after retrieval
 # of an item, retranslate back to either a space or an escaped space.
 # Only do this for cmake
+
+echo "Finding files: "
 
 shopt -s nullglob
 # files is the complete list of mod files to process
@@ -118,20 +139,25 @@ for i in "${files[@]}" ; do
   base_names+=( "$(basename "$i" .mod)" )
 done
 
-echo -n "Mod files:"
 for i in "${files[@]}" ; do
-  dir_name=$(dirname "$i")
-  echo -n " \"$dir_name/${i%.mod}.mod\""
+  echo  "- ${i%.mod}.mod"
 done
-echo ""
-echo ""
-
 
 if [ ! -d "$MODSUBDIR" ] ; then
   echo "Creating '$MODSUBDIR' directory for .o files."
   echo
-  mkdir "$MODSUBDIR"
+  mkdir -p "$MODSUBDIR"
 fi
+
+if [ "$LinkCoreNEURON" = true ] ; then
+  echo "Cleaning files to $MODSUBDIR/cleaned_mod"
+  # Cleaning files
+  mkdir -p "$MODSUBDIR/cleaned_mod"
+  for i in "${files[@]}" ; do
+    "${NMODL}" -o "$MODSUBDIR/cleaned_mod" "$i" passes --convert-neuron > /dev/null
+  done
+fi
+
 
 files=( "${files[@]%.mod}" )
 
@@ -141,6 +167,7 @@ mdir="$PWD"
 # construct file to be included by makefile to specify mod to c rule when
 # executed in $MODSUBDIR (child folder of launch location folder)
 MODMAKE=makemod2c_inc
+echo "Generating $MODMAKE"
 > "$MODMAKE"
 for i in "${files[@]}" ; do
   case "$i" in
@@ -149,9 +176,12 @@ for i in "${files[@]}" ; do
   esac
   base_name="$(basename "$f")"
   dir_name="$(dirname "$f")"
+  if [ "$LinkCoreNEURON" = true ] ; then
+    dir_name="$MODSUBDIR/cleaned_mod"
+  fi
   # Note: indentation for shell lines in make rules must be a tab
   echo "\
-./${base_name// /\\ }.c: ${f// /\\ }.mod
+./${base_name// /\\ }.c: ${dir_name// /\\ }/${base_name}.mod
 	@printf \" -> \$(C_GREEN)NMODL\$(C_RESET) \$<\\\n\"
 	(cd \"$dir_name\"; MODLUNIT=\$(NRNUNITS) \$(NOCMODL) \"$base_name.mod\" -o \"$mdir\")
 
@@ -163,6 +193,7 @@ done
 
 MODOBJS=
 
+echo "Generating mod_func.cpp"
 {
   echo '#include <stdio.h>
 #include "hocdec.h"
@@ -204,23 +235,13 @@ extern "C" {
 #endif'
 } > mod_func.cpp
 
-# call nrnivmodl-core if CoreNEURON is enabled and requested via CLI
-UsingCoreNEURON=false
-@CORENEURON_ENABLED_TRUE@UsingCoreNEURON=true
 if [ "$LinkCoreNEURON" = true ] ; then
-  if [ "$UsingCoreNEURON" = true ] ; then
-    if [ "$#" -gt 1 ] ; then
-        printf "ERROR : when called with -coreneuron only 1 mod dir is accepted.\n"
-        exit 1
-    fi
-    cd "$USER_PWD"
-    "${cnrn_prefix}/bin/nrnivmodl-core" "${UserCOREFLAGS[@]}" "$@"
-    cd "$MODSUBDIR"
-  else
-    printf "ERROR : CoreNEURON support is not enabled!\n"
-    exit 1
-  fi
+  echo "Compiling files with corenrn"
+  cd "$USER_PWD"
+  "${cnrn_prefix}/bin/nrnivmodl-core" "${UserCOREFLAGS[@]}" "$MODSUBDIR/cleaned_mod" > /dev/null 2>&1
+  cd "$MODSUBDIR"
 fi
 
-make -j 4 -f "${bindir}/nrnmech_makefile" "ROOT=${prefix}" "MODOBJFILES=$MODOBJS" "UserLDFLAGS=$UserLDFLAGS" "UserINCFLAGS=$UserINCFLAGS" "LinkCoreNEURON=$LinkCoreNEURON" special &&
+echo "Compiling files with nrn"
+make -j 4 -f "${bindir}/nrnmech_makefile" "ROOT=${prefix}" "MODOBJFILES=$MODOBJS" "UserLDFLAGS=$UserLDFLAGS" "UserINCFLAGS=$UserINCFLAGS" "LinkCoreNEURON=$LinkCoreNEURON" special > /dev/null 2>&1 &&
 echo "Successfully created $MODSUBDIR/special"
