Fixing nrnivmodl-core: Avoid redefined symbols + script startup fixes (BlueBrain/CoreNeuron#133)
* Fixing nrnivmodl-core: dir creation, shbang
* Remove unnecessary mkdir step, create core sub-directory under x86_64
* Avoiding duplicate symbols when using nrnivmodl-core
* Generating libcorenrnmech featuring solve_core()
* Create an intermediate library (corenrnmech, similar to the process of nrnivmodl-core) which
contains the extra mechanisms and a solve_core() launcher, besides all
dependent registration/hook routines (mod_func.cpp and dimplic.cpp)
* Recompile kinderiv dependencies
* Install libcudacoreneuron; link missing
* Set rpath on libcorenrnmech
* Fix for GPU. Simplified build and fixed link flag
* Fixing rpath Origin in Mac and added deploy script
* Remove Wall flags from default compilation
* Cleanup debug messages in GPU implementation

CoreNEURON Repo SHA: BlueBrain/CoreNeuron@8fa8c48708fd8ce73ab060b37fdb2a5ef7b9d425

diff --git a/bin/nrnivmodl-core b/bin/nrnivmodl-core
--- a/bin/nrnivmodl-core
+++ b/bin/nrnivmodl-core
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # -----------------------------------------------------------------------------
 # nrnivmodl-core uses make to compile additonal mod files for coreneuron
 # Copyright 2019 Blue Brain Project
@@ -8,8 +8,10 @@ set -e
 APP_NAME=$(basename $0)
 _PARENT="$(dirname $BASH_SOURCE)/.."
 ROOTDIR=$(perl -e "use Cwd 'abs_path'; print abs_path('$_PARENT')")
+MAKE_OPTIONS="MECH_NAME MECH_VERSION OUTPUT INCFLAGS LINKFLAGS MODS_PATH OPTMODS VERBOSE"
+PARALLELISM=4
 
-while getopts "n:v:o:i:l:ch" OPT; do
+while getopts "n:v:o:i:l:p:chV" OPT; do
     case "$OPT" in
     n)
         params_MECH_NAME="$OPTARG";;
@@ -23,6 +25,10 @@ while getopts "n:v:o:i:l:ch" OPT; do
         params_LINKFLAGS="$OPTARG";;
     c)
         params_OPTMODS="";;
+    V)
+        params_VERBOSE=1;;
+    p)
+        PARALLELISM="$OPTARG";;
     h)
         echo "$APP_NAME [options, ...] [mods_path]"
         echo "Options:"
@@ -31,8 +37,10 @@ while getopts "n:v:o:i:l:ch" OPT; do
         echo "  -o <output_dir> Set the output dir (default: <arch>-core)"
         echo "  -i <incl_flags> Definitions passed to the compiler, typically '-I dir..'"
         echo "  -l <link_flags> Definitions passed to the linker, typically '-Lx -lylib..'"
-        echo "  -c              (clean) Don't use any ADDITIONAL mod built-into coreneuron."
+        echo "  -c              Clean: Don't use any ADDITIONAL mod built-into coreneuron."
         echo "                  By default this only contains halfgap.mod"
+        echo "  -V              Verbose: show commands executed by make"
+        echo "  -p <n_procs>    Make parallelism. Default: 4"
         exit 0;;
     ?)
         exit 1;;
@@ -52,14 +60,25 @@ params_MODS_PATH=$1
 
 make_params=()
 
-for param in MECH_NAME MECH_VERSION OUTPUT INCFLAGS LINKFLAGS MODS_PATH OPTMODS; do
+for param in $MAKE_OPTIONS; do
     var="params_${param}"
     [ "${!var+x}" ] && make_params+=("$param=${!var}")
 done
 
 # warn if no mod files provided
 ls "${params_MODS_PATH:-.}"/*.mod || echo "Warning: No mods found!"
+(
+    set -x
+    make -j$PARALLELISM -f "${ROOTDIR}/share/coreneuron/nrnivmodl_core_makefile" "${make_params[@]}"
+)
 
+# Create a little script to call make install (relinks w right RPATH)
+echo "#!/bin/bash
+set -e
+[ \$# -eq 1 ] || { echo 'Required install destination. Syntax: ' \$(basename \$0) '<directory>'; false; }
 set -x
+make -f \"${ROOTDIR}/share/coreneuron/nrnivmodl_core_makefile\" ${make_params[@]} DESTDIR=\$1 install
+" > nrnivmech_install.sh
+chmod 755 nrnivmech_install.sh
 
-make -j4 -f "${ROOTDIR}/share/coreneuron/nrnivmodl_core_makefile" "${make_params[@]}"
+echo "mods built successfully. Install script written to nrnivmech_install.sh"
