CI config cleanup and py3.10 updates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,19 +5,23 @@ orbs:
 
 jobs:
   manylinux2014-aarch64:
+
     parameters:
-      cibw_build:
+      NRN_PYTHON_VERSION:
+        type: string
+      NRN_NIGHTLY_UPLOAD:
         type: string
 
     machine:
       image: ubuntu-2004:202101-01
+
     resource_class: arm.medium
+
     steps:
       - checkout
       - run:
           name: Build manylinux AArch64 wheel
           command: |
-            uname -a
             docker run --rm \
                 -w /root/nrn \
                 -v $PWD:/root/nrn \
@@ -28,18 +32,55 @@ jobs:
                 -e NEURON_WHEEL_VERSION \
                 -e NRN_BUILD_FOR_UPLOAD=1 \
                 'neuronsimulator/neuron_wheel:latest-aarch64' \
-                packaging/python/build_wheels.bash linux << parameters.cibw_build >> coreneuron
-      - run:
-          name: Test manylinux AArch64 wheel
-          command: |
-            sudo apt update
-            sudo apt install -y mpich openmpi-bin libopenmpi-dev libmpich-dev
-            env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.0
-            pyenv global 3.9.0
-            packaging/python/test_wheels.sh $(which python) $(ls -t wheelhouse/*.whl)
+                packaging/python/build_wheels.bash linux << parameters.NRN_PYTHON_VERSION >> coreneuron
+
       - store_artifacts:
           path: ./wheelhouse
           destination: artifacts
+
+      - run:
+          name: Test manylinux AArch64 wheel
+          command: |
+
+            # install mpi dependencies
+            sudo apt update
+            sudo apt install -y mpich openmpi-bin libopenmpi-dev libmpich-dev
+
+            # choose available python versions from pyenv
+            pyenv_py_ver=""
+            case << parameters.NRN_PYTHON_VERSION >> in
+              36) pyenv_py_ver="3.6.12" ;;
+              37) pyenv_py_ver="3.7.9" ;;
+              38) pyenv_py_ver="3.8.7" ;;
+              39) pyenv_py_ver="3.9.1" ;;
+              310) pyenv_py_ver="3.10.1" ;;
+              *) echo "Error: pyenv python version not specified!" && exit 1;;
+            esac
+
+            # install python dependencies: .10 is not available pyenv
+            if [ "<< parameters.NRN_PYTHON_VERSION >>" == "310" ]; then
+              sudo apt install software-properties-common -y
+              sudo add-apt-repository ppa:deadsnakes/ppa -y
+              sudo apt install python3.10 libpython3.10 python3.10-venv
+              export PYTHON_EXE=$(which python3.10)
+            else
+              env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $pyenv_py_ver --force
+              pyenv global $pyenv_py_ver
+              export PYTHON_EXE=$(which python)
+            fi
+
+            # test wheel
+            packaging/python/test_wheels.sh $PYTHON_EXE $(ls -t wheelhouse/*.whl)
+
+      - run:
+          name: Upload nightly wheel to pypi.org
+          command: |
+            if [ "<< parameters.NRN_NIGHTLY_UPLOAD >>" == "true" ]; then
+              python -m pip install twine
+              python -m twine upload --verbose --skip-existing -u $TWINE_USERNAME -p $TWINE_PASSWORD  wheelhouse/*.whl
+            else
+              echo "Skipping pypi.org upload!"
+            fi
 
 workflows:
 
@@ -48,7 +89,8 @@ workflows:
       - manylinux2014-aarch64:
           matrix:
             parameters:
-              cibw_build: ["39"]
+              NRN_PYTHON_VERSION: ["310"]
+              NRN_NIGHTLY_UPLOAD: ["false"]
 
   nightly:
     triggers:
@@ -57,25 +99,10 @@ workflows:
           filters:
             branches:
               only:
-                #- master   #disable master builds until PR is merged
-                - aarch64_wheel
-                - pramodk/aarch64_wheel
+                - master
     jobs:
       - manylinux2014-aarch64:
           matrix:
             parameters:
-              cibw_build: ["310"]
-  weekly:
-    triggers:
-      - schedule:
-          cron: "0 0 * * 0"
-          filters:
-            branches:
-              only:
-                #- master   #disable master builds until PR is merged
-                - aarch64_wheel
-    jobs:
-      - manylinux2014-aarch64:
-          matrix:
-            parameters:
-              cibw_build: ["36", "37", "38", "39", "310"]
+              NRN_PYTHON_VERSION: ["36", "37", "38", "39", "310"]
+              NRN_NIGHTLY_UPLOAD: ["true"]
