Correcting statistics for counting events originated by spike exchange. Adding second real production test.
Change-Id: Iff49baa9e13e1daf873d631e699c1d00e4054009

CoreNEURON Repo SHA: BlueBrain/CoreNeuron@7fda40e5e0d7ce14f51d190f81f1d1537bd58abe

diff --git a/tests/production/production_test.sh.in b/tests/production/production_test.sh.in
--- a/tests/production/production_test.sh.in
+++ b/tests/production/production_test.sh.in
@@ -1,5 +1,12 @@
 #! /bin/sh 
 
+reference=/gpfs/bbp.cscs.ch/project/proj16/coreneuron/data/@SIM_NAME@/reference_output/out.dat.ref
+if [ ! -f $reference ]
+then
+  echo "No reference output file. Test failed!"
+  exit 1
+fi
+
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:@CMAKE_BINARY_DIR@/lib
 export OMP_NUM_THREADS=64
 
@@ -31,7 +38,7 @@ fi
 
 cat out[0-9]*.dat > out_cn.dat
 sort -k 1n,1n -k 2n,2n out_cn.dat > sort_out.dat
-diff sort_out.dat /gpfs/bbp.cscs.ch/project/proj16/coreneuron/data/93k_3columns_O1_3m/reference_output/@SIM_NAME@/out.dat.ref > diff.dat
+diff sort_out.dat $reference > diff.dat
 
 if [ -s diff.dat ] 
 then
